AWSTemplateFormatVersion: 2010-09-09
Description: Lacework AWS CloudTrail and Config Security Audit Integration
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Parameters:
          - ResourceNamePrefix
          - KMSKeyARN
          - CrossAccountRoleARN
          - ExternalID
          - ApiToken
    ParameterLabels:
      ResourceNamePrefix:
        default: Resource name prefix
      KMSKeyARN:
        default: KMS Key ARN
      CrossAccountRoleARN:
        default: Cross-Account IAM Role ARN
      ExternalID:
        default: External ID
      ApiToken:
        default: API Token
Parameters:
  ResourceNamePrefix:
    Description: >-
      [DO NOT CHANGE] Names of resources created by the stack will be prefixed
      with this value to ensure uniqueness.
    Type: String
    Default: lacework-vonage
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix value.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  KMSKeyARN:
    Description: >-
      [REQUIRED] KMS Key ARN that will be used to encrypt the cloudtrail
      resources. (Created in Step 1).
    Type: String
    MinLength: '40'
    AllowedPattern: '^arn:aws:kms:.*$'
    MaxLength: '1224'
  CrossAccountRoleARN:
    Description: >-
      [REQUIRED] Cross-account access role ARN to share with Lacework for
      CloudTrail integration. (Created in Step 1).
    Type: String
    MinLength: '40'
    AllowedPattern: '^arn:aws:iam::.*$'
    MaxLength: '1224'
  ExternalID:
    Description: >-
      [REQUIRED] The external ID of the cross-account access role (Created in
      Step 1).
    Type: String
    MinLength: '2'
    MaxLength: '1224'
    AllowedPattern: .+
    ConstraintDescription: >-
      Invalid ExternalID value.  Must be at least 2 characters and no more than
      1224.'
  ApiToken:
    Description: '[REQUIRED] The token required for making API requests with Lacework.'
    Type: String
    MinLength: '1'
    AllowedPattern: .+
    ConstraintDescription: A valid API Token is required
Resources:
  LaceworkLogs:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref KMSKeyARN
      VersioningConfiguration:
        Status: Enabled
  LaceworkCWSBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join 
        - ''
        - - lacework-vonage-ct-
          - !Ref 'AWS::AccountId'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref KMSKeyARN
      LoggingConfiguration:
        DestinationBucketName: !Ref LaceworkLogs
        LogFilePrefix: lacework-logging
      VersioningConfiguration:
        Status: Enabled
  LaceworkCWSBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref LaceworkCWSBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: LaceworkCWSBucketPolicy
        Statement:
          - Sid: CloudTrailAclCheck
            Action: 's3:GetBucketAcl'
            Effect: Allow
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LaceworkCWSBucket
            Principal:
              Service: cloudtrail.amazonaws.com
          - Sid: CloudTrailWrite
            Action: 's3:PutObject'
            Effect: Allow
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LaceworkCWSBucket
                - /AWSLogs/
                - !Ref 'AWS::AccountId'
                - /*
            Principal:
              Service: cloudtrail.amazonaws.com
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
              Bool:
                'aws:SecureTransport': 'true'
  LaceworkCWSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Join 
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcws'
      KmsMasterKeyId: !Ref KMSKeyARN
  LaceworkCWSTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudTrailPublish
            Action: 'SNS:Publish'
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource: '*'
      Topics:
        - !Ref LaceworkCWSTopic
  LaceworkCWSTrail:
    Type: 'AWS::CloudTrail::Trail'
    DependsOn:
      - LaceworkCWSTopicPolicy
      - LaceworkCWSBucketPolicy
    Properties:
      TrailName: !Join 
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcws'
      S3BucketName: !Ref LaceworkCWSBucket
      SnsTopicName: !GetAtt 
        - LaceworkCWSTopic
        - TopicName
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      IsLogging: true
      KMSKeyId: !Ref KMSKeyARN
  LaceworkCWSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Join 
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcws'
      KmsMasterKeyId: !Ref KMSKeyARN
  LaceworkCWSQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AwsSnsAccess
            Effect: Allow
            Principal: '*'
            Action:
              - 'sqs:SendMessage'
            Resource: '*'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Ref LaceworkCWSTopic
      Queues:
        - !Ref LaceworkCWSQueue
  LaceworkCWSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !GetAtt 
        - LaceworkCWSQueue
        - Arn
      Protocol: sqs
      TopicArn: !Ref LaceworkCWSTopic
  LaceworkSnsCustomResource:
    Type: 'Custom::LaceworkSnsCustomResource'
    DependsOn:
      - LaceworkCWSQueuePolicy
      - LaceworkCWSQueue
    Properties:
      Type: AWS_CT_CFG
      ServiceToken: !Join 
        - ''
        - - 'arn:aws:sns:'
          - !Ref 'AWS::Region'
          - ':434813966438:prodn-customer-cloudformation'
      IntegrationName: !Ref 'AWS::StackName'
      RoleArn: !Ref CrossAccountRoleARN
      ExternalId: !Ref ExternalID
      SqsQueueUrl: !Ref LaceworkCWSQueue
      ApiToken: !Ref ApiToken
      Account: vonage
      TemplateVersion: '1.1'
      AWSAccountId: !Ref 'AWS::AccountId'
Outputs:
  TemplateVersion:
    Description: Template version
    Value: '1.1'
