AWSTemplateFormatVersion: 2010-09-09
Description: Lacework AWS CSPM - IAM Role & Policy Creation
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Parameters:
          - ResourceNamePrefix
          - KMSKeyARN
          - SQSQueueURL
          - ApiToken
          - ExternalID
    ParameterLabels:
      ResourceNamePrefix:
        default: Resource name prefix
      KMSKeyARN:
        default: KMS Key ARN
      SQSQueueURL:
        default: SQS Queue URL
      ApiToken:
        default: API Token
      ExternalID:
        default: ExternalID
Parameters:
  ResourceNamePrefix:
    Description: >-
      Names of resources created by the stack will be prefixed with this value
      to ensure uniqueness.
    Type: String
    Default: lacework-vonage
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix value.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  KMSKeyARN:
    Description: >-
      [REQUIRED] KMS Key ARN that is being used to encrypt the cloudtrail
      resources. (Created in Step 1).
    Type: String
    MinLength: '40'
    AllowedPattern: '^arn:aws:kms:.*$'
    MaxLength: '1224'
  SQSQueueURL:
    Description: >-
      [REQUIRED] The SQS Queue URL from the cloudtrail stack. (Created in Step
      1).
    Type: String
    MinLength: '40'
    AllowedPattern: '^https://sqs.*.amazonaws.com/153466455358/lacework-vonage-laceworkcws$'
    MaxLength: '1224'
  ApiToken:
    Description: '[REQUIRED] The token required for making API requests with Lacework.'
    Type: String
    MinLength: '1'
    AllowedPattern: .+
    ConstraintDescription: A valid API Token is required
  ExternalID:
    Description: >-
      The cross-account access role created by the stack will use this value for
      its ExternalID.
    Type: String
    Default: VON8ab7cfd0
    MinLength: '2'
    MaxLength: '1224'
    AllowedValues:
      - VON8ab7cfd0
    ConstraintDescription: Invalid ExternalID value.  Must be equal to 'VON8ab7cfd0'
Resources:
  LaceworkCWSSACrossAccountAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join 
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcwssarole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - '434813966438'
                  - ':root'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalID
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
  LaceworkCWSPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: LaceworkCWSPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ConsumeNotifications
            Action:
              - 'sqs:GetQueueAttributes'
              - 'sqs:GetQueueUrl'
              - 'sqs:DeleteMessage'
              - 'sqs:ReceiveMessage'
            Effect: Allow
            Resource: !Join 
              - ''
              - - 'arn:aws:sqs:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':'
                - !Ref ResourceNamePrefix
                - '-laceworkcws'
          - Sid: ListLogFiles
            Action:
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - lacework-vonage-ct-
                  - !Ref 'AWS::AccountId'
            Condition:
              StringLike:
                's3:prefix':
                  - '*AWSLogs/'
          - Sid: ReadLogFiles
            Action:
              - 's3:Get*'
            Effect: Allow
            Resource:
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - lacework-vonage-ct-
                  - !Ref 'AWS::AccountId'
                  - /*
          - Sid: GetAccountAlias
            Action:
              - 'iam:ListAccountAliases'
            Effect: Allow
            Resource: '*'
          - Sid: DecryptLogFiles
            Action:
              - 'kms:Decrypt'
            Effect: Allow
            Resource: !Ref KMSKeyARN
          - Sid: Debug
            Action:
              - 'cloudtrail:DescribeTrails'
              - 'cloudtrail:GetTrail'
              - 'cloudtrail:GetTrailStatus'
              - 'cloudtrail:ListPublicKeys'
              - 'eks:ListTagsForResource'
              - 's3:GetBucketAcl'
              - 's3:GetBucketPolicy'
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
              - 's3:GetBucketLogging'
              - 'sns:GetSubscriptionAttributes'
              - 'sns:GetTopicAttributes'
              - 'sns:ListSubscriptions'
              - 'sns:ListSubscriptionsByTopic'
              - 'sns:ListTopics'
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref LaceworkCWSSACrossAccountAccessRole
  LaceworkAuditPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: LaceworkAuditPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: GetBucketPublicAccessBlock
            Action:
              - 's3:GetBucketPublicAccessBlock'
            Effect: Allow
            Resource: '*'
          - Sid: GetEbsEncryptionByDefault
            Action:
              - 'ec2:GetEbsEncryptionByDefault'
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref LaceworkCWSSACrossAccountAccessRole
  LaceworkSnsCustomResource:
    Type: 'Custom::LaceworkSnsCustomResource'
    DependsOn:
      - LaceworkCWSSACrossAccountAccessRole
      - LaceworkCWSPolicy
      - LaceworkAuditPolicy
    Properties:
      Type: AWS_CT_CFG
      ServiceToken: !Join 
        - ''
        - - 'arn:aws:sns:'
          - !Ref 'AWS::Region'
          - ':434813966438:prodn-customer-cloudformation'
      IntegrationName: !Ref 'AWS::StackName'
      RoleArn: !GetAtt 
        - LaceworkCWSSACrossAccountAccessRole
        - Arn
      ExternalId: !Ref ExternalID
      SqsQueueUrl: !Ref SQSQueueURL
      ApiToken: !Ref ApiToken
      Account: vonage
      TemplateVersion: '1.1'
      AWSAccountId: !Ref 'AWS::AccountId'
Outputs:
  TemplateVersion:
    Description: Template version
    Value: '1.1'
